In [2]:
import pandas as pd

In [3]:
path_to_csv = ['./submissions/submission-char-recog-v1.csv','./submissions/submission-ctc.csv','./submissions/submission-yolo.csv']

In [4]:
df = pd.read_csv(path_to_csv[0])
df1 = pd.read_csv(path_to_csv[1])
df2 = pd.read_csv(path_to_csv[2])

In [5]:
df

    Unnamed: 0     Name of File Vehicleregistrationplatebymodel
0            0    DataTest1.jpg                        A07034OE
1            1    DataTest2.jpg                          A9388E
2            2    DataTest3.jpg                           B16TB
3            3    DataTest4.jpg                        B16611K2
4            4    DataTest5.jpg                      EA01112AHE
..         ...              ...                             ...
95          95   DataTest96.jpg                          13BE1J
96          96   DataTest97.jpg                        AB8644P6
97          97   DataTest98.jpg                        AG9718EG
98          98   DataTest99.jpg                         O15U9UO
99          99  DataTest100.jpg                         B1408RX

[100 rows x 3 columns]

### length voting

In [6]:
from collections import Counter

answer = df['Vehicleregistrationplatebymodel'].tolist()
answer1 = df1['Vehicleregistrationplatebymodel'].tolist()
answer2 = df2['Vehicleregistrationplatebymodel'].tolist()

for i in range(len(answer)):
  predictions = [answer[i], answer1[i], answer2[i]]

  # Count the occurrences of each length
  lengths = [len(pred) for pred in predictions]
  votes = Counter(lengths)

  # Get the most common length
  final_length = votes.most_common(1)[0][0]

  print(f'DataTest{i+1}: {final_length}')

DataTest1: 8
DataTest2: 7
DataTest3: 5
DataTest4: 8
DataTest5: 7
DataTest6: 9
DataTest7: 8
DataTest8: 8
DataTest9: 8
DataTest10: 8
DataTest11: 8
DataTest12: 8
DataTest13: 8
DataTest14: 7
DataTest15: 8
DataTest16: 8
DataTest17: 7
DataTest18: 8
DataTest19: 8
DataTest20: 4
DataTest21: 6
DataTest22: 8
DataTest23: 8
DataTest24: 5
DataTest25: 8
DataTest26: 8
DataTest27: 6
DataTest28: 7
DataTest29: 6
DataTest30: 7
DataTest31: 6
DataTest32: 8
DataTest33: 8
DataTest34: 9
DataTest35: 8
DataTest36: 7
DataTest37: 8
DataTest38: 8
DataTest39: 8
DataTest40: 7
DataTest41: 8
DataTest42: 7
DataTest43: 8
DataTest44: 7
DataTest45: 8
DataTest46: 8
DataTest47: 8
DataTest48: 9
DataTest49: 8
DataTest50: 8
DataTest51: 8
DataTest52: 8
DataTest53: 8
DataTest54: 7
DataTest55: 8
DataTest56: 8
DataTest57: 7
DataTest58: 7
DataTest59: 5
DataTest60: 8
DataTest61: 9
DataTest62: 6
DataTest63: 6
DataTest64: 8
DataTest65: 7
DataTest66: 6
DataTest67: 8
DataTest68: 8
DataTest69: 8
DataTest70: 8
DataTest71: 8
DataTest72: 8
DataTest73: 8
DataTest74: 8
DataTest75: 7
DataTest76: 8
DataTest77: 8
DataTest78: 8
DataTest79: 7
DataTest80: 8
DataTest81: 7
DataTest82: 8
DataTest83: 6
DataTest84: 8
DataTest85: 8
DataTest86: 8
DataTest87: 8
DataTest88: 8
DataTest89: 6
DataTest90: 8
DataTest91: 8
DataTest92: 8
DataTest93: 8
DataTest94: 8
DataTest95: 8
DataTest96: 6
DataTest97: 8
DataTest98: 8
DataTest99: 7
DataTest100: 7

## label voting

In [12]:
from collections import Counter

answer = df['Vehicleregistrationplatebymodel'].tolist()
answer1 = df1['Vehicleregistrationplatebymodel'].tolist()
answer2 = df2['Vehicleregistrationplatebymodel'].tolist()

final_results = []

for i in range(len(answer)):
    predictions = [answer[i], answer1[i], answer2[i]]

    # Count the occurrences of each length
    lengths = [len(pred) for pred in predictions]
    votes = Counter(lengths)

    # Get the most common length
    final_length = votes.most_common(1)[0][0]

    # Transpose the data to get the predictions for each position
    predictions = list(map(list, zip(*predictions)))

    # Initialize the final prediction
    final_prediction = []

    # Loop through the predictions for each position
    for preds in predictions:
        # Count the votes for each character
        votes = Counter(preds)
        
        # Get the character with the most votes
        final_char = votes.most_common(1)[0][0]
        
        # Add the character to the final prediction
        final_prediction.append(final_char)

    # # Truncate or pad the final prediction to match the final length
    # if len(final_prediction) > final_length:
    #     final_prediction = final_prediction[:final_length]
    # elif len(final_prediction) < final_length:
    #     final_prediction += [''] * (final_length - len(final_prediction))

    final_label = ''.join(final_prediction)

    final_results.append(final_label)

    print(f'DataTest{i+1}: {final_label}, length: {final_length}')

DataTest1: A07034OE, length: 8
DataTest2: A9388E, length: 7
DataTest3: B16TB, length: 5
DataTest4: B1661TKZ, length: 8
DataTest5: AA01112, length: 7
DataTest6: B1L10, length: 9
DataTest7: B1064TFR, length: 8
DataTest8: B1395TJW, length: 8
DataTest9: B1270RF, length: 8
DataTest10: B1736BYH, length: 8
DataTest11: B162TBI, length: 8
DataTest12: B1678WZ, length: 8
DataTest13: AD9313SS, length: 8
DataTest14: B1036UL, length: 7
DataTest15: B1801TZS, length: 8
DataTest16: B1474TJS, length: 8
DataTest17: B1939PU, length: 7
DataTest18: B1260TZT, length: 8
DataTest19: B1376TJO, length: 8
DataTest20: B10, length: 4
DataTest21: AB6121, length: 6
DataTest22: B1236PZM, length: 8
DataTest23: AE8644P, length: 8
DataTest24: B1JKT, length: 5
DataTest25: A4708L1, length: 8
DataTest26: B1131EKG, length: 8
DataTest27: B10377, length: 6
DataTest28: B1036UL, length: 7
DataTest29: A080, length: 6
DataTest30: A9192ZM, length: 7
DataTest31: BB20, length: 6
DataTest32: B1643TRO, length: 8
DataTest33: B1390TJ0, length: 8
DataTest34: AB2611V0, length: 9
DataTest35: B1860EF, length: 8
DataTest36: A8749FS, length: 7
DataTest37: B1566FON, length: 8
DataTest38: B1063SJQ, length: 8
DataTest39: B1254TFX, length: 8
DataTest40: B10368J, length: 7
DataTest41: AB49231Y, length: 8
DataTest42: B15U9UO, length: 7
DataTest43: B1937T, length: 8
DataTest44: B12, length: 7
DataTest45: B1026TV2, length: 8
DataTest46: B1724PYW, length: 8
DataTest47: B1102SII, length: 8
DataTest48: A077034E, length: 9
DataTest49: AB43E2, length: 8
DataTest50: B1895EJB, length: 8
DataTest51: B1786UJT, length: 8
DataTest52: B1549RFS, length: 8
DataTest53: B1869EOF, length: 8
DataTest54: B17131, length: 7
DataTest55: B1063SP, length: 8
DataTest56: B1661TKZ, length: 8
DataTest57: A8014V, length: 7
DataTest58: B1873YU, length: 7
DataTest59: B170, length: 5
DataTest60: B1422BK, length: 8
DataTest61: AB52183, length: 9
DataTest62: AD418U, length: 6
DataTest63: B1157Y, length: 6
DataTest64: B1233RF, length: 8
DataTest65: B1031NI, length: 7
DataTest66: A099J, length: 6
DataTest67: B1683SEY, length: 8
DataTest68: AA000, length: 8
DataTest69: B1241SS, length: 8
DataTest70: B1632TJJ, length: 8
DataTest71: B1907ELR, length: 8
DataTest72: B1815TJ0, length: 8
DataTest73: B1734UJ1, length: 8
DataTest74: B1743EYF, length: 8
DataTest75: 61075QO, length: 7
DataTest76: AM2JJJ, length: 8
DataTest77: B1523TJT, length: 8
DataTest78: B1157SS, length: 8
DataTest79: B17131, length: 7
DataTest80: B1361TJS, length: 8
DataTest81: A9388E, length: 7
DataTest82: B1532NKY, length: 8
DataTest83: B18000, length: 6
DataTest84: B1411T, length: 8
DataTest85: AB377B7K, length: 8
DataTest86: B1319R, length: 8
DataTest87: B1903RF0, length: 8
DataTest88: AB29580H, length: 8
DataTest89: AD418U, length: 6
DataTest90: B1885TLP, length: 8
DataTest91: B1634SS, length: 8
DataTest92: AB35118, length: 8
DataTest93: B1726U0, length: 8
DataTest94: B1820TJV, length: 8
DataTest95: B1619UF, length: 8
DataTest96: 13BE1J, length: 6
DataTest97: AB8644PK, length: 8
DataTest98: AG9718EG, length: 8
DataTest99: B15U9UO, length: 7
DataTest100: B1408RX, length: 7

In [13]:
final_results

['A07034OE',
 'A9388E',
 'B16TB',
 'B1661TKZ',
 'AA01112',
 'B1L10',
 'B1064TFR',
 'B1395TJW',
 'B1270RF',
 'B1736BYH',
 'B162TBI',
 'B1678WZ',
 'AD9313SS',
 'B1036UL',
 'B1801TZS',
 'B1474TJS',
 'B1939PU',
 'B1260TZT',
 'B1376TJO',
 'B10',
 'AB6121',
 'B1236PZM',
 'AE8644P',
 'B1JKT',
 'A4708L1',
 'B1131EKG',
 'B10377',
 'B1036UL',
 'A080',
 'A9192ZM',
 'BB20',
 'B1643TRO',
 'B1390TJ0',
 'AB2611V0',
 'B1860EF',
 'A8749FS',
 'B1566FON',
 'B1063SJQ',
 'B1254TFX',
 'B10368J',
 'AB49231Y',
 'B15U9UO',
 'B1937T',
 'B12',
 'B1026TV2',
 'B1724PYW',
 'B1102SII',
 'A077034E',
 'AB43E2',
 'B1895EJB',
 'B1786UJT',
 'B1549RFS',
 'B1869EOF',
 'B17131',
 'B1063SP',
 'B1661TKZ',
 'A8014V',
 'B1873YU',
 'B170',
 'B1422BK',
 'AB52183',
 'AD418U',
 'B1157Y',
 'B1233RF',
 'B1031NI',
 'A099J',
 'B1683SEY',
 'AA000',
 'B1241SS',
 'B1632TJJ',
 'B1907ELR',
 'B1815TJ0',
 'B1734UJ1',
 'B1743EYF',
 '61075QO',
 'AM2JJJ',
 'B1523TJT',
 'B1157SS',
 'B17131',
 'B1361TJS',
 'A9388E',
 'B1532NKY',
 'B18000',
 'B1411T',
 'AB377B7K',
 'B1319R',
 'B1903RF0',
 'AB29580H',
 'AD418U',
 'B1885TLP',
 'B1634SS',
 'AB35118',
 'B1726U0',
 'B1820TJV',
 'B1619UF',
 '13BE1J',
 'AB8644PK',
 'AG9718EG',
 'B15U9UO',
 'B1408RX']

In [14]:
files = df['Name of File'].tolist()
files

['DataTest1.jpg',
 'DataTest2.jpg',
 'DataTest3.jpg',
 'DataTest4.jpg',
 'DataTest5.jpg',
 'DataTest6.jpg',
 'DataTest7.jpg',
 'DataTest8.jpg',
 'DataTest9.jpg',
 'DataTest10.jpg',
 'DataTest11.jpg',
 'DataTest12.jpg',
 'DataTest13.jpg',
 'DataTest14.jpg',
 'DataTest15.jpg',
 'DataTest16.jpg',
 'DataTest17.jpg',
 'DataTest18.jpg',
 'DataTest19.jpg',
 'DataTest20.jpg',
 'DataTest21.jpg',
 'DataTest22.jpg',
 'DataTest23.jpg',
 'DataTest24.jpg',
 'DataTest25.jpg',
 'DataTest26.jpg',
 'DataTest27.jpg',
 'DataTest28.jpg',
 'DataTest29.jpg',
 'DataTest30.jpg',
 'DataTest31.jpg',
 'DataTest32.jpg',
 'DataTest33.jpg',
 'DataTest34.jpg',
 'DataTest35.jpg',
 'DataTest36.jpg',
 'DataTest37.jpg',
 'DataTest38.jpg',
 'DataTest39.jpg',
 'DataTest40.jpg',
 'DataTest41.jpg',
 'DataTest42.jpg',
 'DataTest43.jpg',
 'DataTest44.jpg',
 'DataTest45.jpg',
 'DataTest46.jpg',
 'DataTest47.jpg',
 'DataTest48.jpg',
 'DataTest49.jpg',
 'DataTest50.jpg',
 'DataTest51.jpg',
 'DataTest52.jpg',
 'DataTest53.jpg',
 'DataTest54.jpg',
 'DataTest55.jpg',
 'DataTest56.jpg',
 'DataTest57.jpg',
 'DataTest58.jpg',
 'DataTest59.jpg',
 'DataTest60.jpg',
 'DataTest61.jpg',
 'DataTest62.jpg',
 'DataTest63.jpg',
 'DataTest64.jpg',
 'DataTest65.jpg',
 'DataTest66.jpg',
 'DataTest67.jpg',
 'DataTest68.jpg',
 'DataTest69.jpg',
 'DataTest70.jpg',
 'DataTest71.jpg',
 'DataTest72.jpg',
 'DataTest73.jpg',
 'DataTest74.jpg',
 'DataTest75.jpg',
 'DataTest76.jpg',
 'DataTest77.jpg',
 'DataTest78.jpg',
 'DataTest79.jpg',
 'DataTest80.jpg',
 'DataTest81.jpg',
 'DataTest82.jpg',
 'DataTest83.jpg',
 'DataTest84.jpg',
 'DataTest85.jpg',
 'DataTest86.jpg',
 'DataTest87.jpg',
 'DataTest88.jpg',
 'DataTest89.jpg',
 'DataTest90.jpg',
 'DataTest91.jpg',
 'DataTest92.jpg',
 'DataTest93.jpg',
 'DataTest94.jpg',
 'DataTest95.jpg',
 'DataTest96.jpg',
 'DataTest97.jpg',
 'DataTest98.jpg',
 'DataTest99.jpg',
 'DataTest100.jpg']

In [15]:
submit = pd.DataFrame({'Name of File': files, 'Vehicleregistrationplatebymodel': final_results})
submit

       Name of File Vehicleregistrationplatebymodel
0     DataTest1.jpg                        A07034OE
1     DataTest2.jpg                          A9388E
2     DataTest3.jpg                           B16TB
3     DataTest4.jpg                        B1661TKZ
4     DataTest5.jpg                         AA01112
..              ...                             ...
95   DataTest96.jpg                          13BE1J
96   DataTest97.jpg                        AB8644PK
97   DataTest98.jpg                        AG9718EG
98   DataTest99.jpg                         B15U9UO
99  DataTest100.jpg                         B1408RX

[100 rows x 2 columns]

In [11]:
submit.to_csv('./submissions/submission-major.csv')